services:
  - type: web
    name: your-doctor-app
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn YourDoctor.wsgi:application
    envVars:
      - key: DEBUG
        value: "false"
      - key: ALLOWED_HOSTS
        value: "mlprojectindjango.onrender.com"
